package constants

import "time"

const (
	MAX_EXPECTATION                     = 10 * time.Second
	CUSTOM_MAX_EXPECTATION_GRAPHQL      = 1 * time.Second
	CUSTOM_MAX_EXPECTATION_ACTIVE_USERS = 40 * time.Second

	SITE = "https://shikimori.io/api/"

	TARGET_TYPE_ANIME = "Anime"
	TARGET_TYPE_MANGA = "Manga"

	SEASON_198x                = "198x"
	SEASON_199x                = "199x"
	SEASON_2000_2010           = "2000_2010"
	SEASON_2010_2014           = "2010_2014"
	SEASON_2015_2019           = "2015_2019"
	SEASON_2020_2021           = "2020_2021"
	SEASON_2022                = "2022"
	SEASON_2023                = "2023"
	SEASON_198x_NOT_EQUAL      = "!198x"
	SEASON_199x_NOT_EQUAL      = "!199x"
	SEASON_2000_2010_NOT_EQUAL = "!2000_2010"
	SEASON_2010_2014_NOT_EQUAL = "!2010_2014"
	SEASON_2015_2019_NOT_EQUAL = "!2015_2019"
	SEASON_2020_2021_NOT_EQUAL = "!2020_2021"
	SEASON_2022_NOT_EQUAL      = "!2022"
	SEASON_2023_NOT_EQUAL      = "!2023"

	MY_LIST_PLANNED    = "planned"
	MY_LIST_WATCHING   = "watching"
	MY_LIST_REWATCHING = "rewatching"
	MY_LIST_COMPLETED  = "completed"
	MY_LIST_ON_HOLD    = "on_hold"
	MY_LIST_DROPPED    = "dropped"

	TOPIC_FORUM_ALL         = "all"
	TOPIC_FORUM_COSPLAY     = "cosplay"
	TOPIC_FORUM_ANIMANGA    = "animanga"
	TOPIC_FORUM_SITE        = "site"
	TOPIC_FORUM_GAMES       = "games"
	TOPIC_FORUM_VN          = "vn"
	TOPIC_FORUM_CONTEST     = "contest"
	TOPIC_FORUM_OFFTOPIC    = "offtopic"
	TOPIC_FORUM_CLUBS       = "clubs"
	TOPIC_FORUM_MYCLUBS     = "my_clubs"
	TOPIC_FORUM_CRITIQUES   = "critiques"
	TOPIC_FORUM_NEWS        = "news"
	TOPIC_FORUM_COLLECTIONS = "collections"
	TOPIC_FORUM_ARTICLES    = "articles"

	TOPIC_LINKED_TYPE_ANIME          = "Anime"
	TOPIC_LINKED_TYPE_MANGA          = "Manga"
	TOPIC_LINKED_TYPE_RANOBE         = "Ranobe"
	TOPIC_LINKED_TYPE_CHARACTER      = "Character"
	TOPIC_LINKED_TYPE_PERSON         = "Person"
	TOPIC_LINKED_TYPE_CLUB           = "Club"
	TOPIC_LINKED_TYPE_CLUBPAGE       = "ClubPage"
	TOPIC_LINKED_TYPE_CRITIQUE       = "Critique"
	TOPIC_LINKED_TYPE_REVIEW         = "Review"
	TOPIC_LINKED_TYPE_CONTEST        = "Contest"
	TOPIC_LINKED_TYPE_COSPLAYGALLYRY = "CosplayGallery"
	TOPIC_LINKED_TYPE_COLLECTION     = "Collection"
	TOPIC_LINKED_TYPE_ARTICLE        = "Article"

	MESSAGE_TYPE_INBOX         = "inbox"
	MESSAGE_TYPE_PRIVATE       = "private"
	MESSAGE_TYPE_SENT          = "sent"
	MESSAGE_TYPE_NEWS          = "news"
	MESSAGE_TYPE_NOTIFICATIONS = "notifications"

	ANIME_ORDER_ID         = "id"
	ANIME_ORDER_RANKED     = "ranked"
	ANIME_ORDER_KIND       = "kind"
	ANIME_ORDER_POPULARITY = "popularity"
	ANIME_ORDER_NAME       = "name"
	ANIME_ORDER_AIRED_ON   = "aired_on"
	ANIME_ORDER_EPISODES   = "episodes"
	ANIME_ORDER_STATUS     = "status"

	ANIME_KIND_MOVIE             = "movie"
	ANIME_KIND_MOVIE_NOT_EQUAL   = "!movie"
	ANIME_KIND_OVA               = "ova"
	ANIME_KIND_ONA               = "ona"
	ANIME_KIND_OVA_NOT_EQUAL     = "!ova"
	ANIME_KIND_ONA_NOT_EQUAL     = "!ona"
	ANIME_KIND_SPECIAL           = "special"
	ANIME_KIND_SPECIAL_NOT_EQUAL = "!special"
	ANIME_KIND_MUSIC             = "music"
	ANIME_KIND_MUSIC_NOT_EQUAL   = "!music"
	ANIME_KIND_TV                = "tv"
	ANIME_KIND_TV_13             = "tv_13"
	ANIME_KIND_TV_24             = "tv_24"
	ANIME_KIND_TV_48             = "tv_48"
	ANIME_KIND_TV_NOT_EQUAL      = "!tv"
	ANIME_KIND_TV_13_NOT_EQUAL   = "!tv_13"
	ANIME_KIND_TV_24_NOT_EQUAL   = "!tv_24"
	ANIME_KIND_TV_48_NOT_EQUAL   = "!tv_48"

	ANIME_STATUS_ANONS              = "anons"
	ANIME_STATUS_ANONS_NOT_EQUAL    = "!anons"
	ANIME_STATUS_ONGOING            = "ongoing"
	ANIME_STATUS_ONGOING_NOT_EQUAL  = "!ongoing"
	ANIME_STATUS_RELEASED           = "released"
	ANIME_STATUS_RELEASED_NOT_EQUAL = "!released"

	ANIME_RATING_NONE             = "none"
	ANIME_RATING_G                = "g"
	ANIME_RATING_PG               = "pg"
	ANIME_RATING_PG_13            = "pg_13"
	ANIME_RATING_R                = "r"
	ANIME_RATING_R_PLUS           = "r_plus"
	ANIME_RATING_RX               = "rx"
	ANIME_RATING_G_NOT_EQUAL      = "!g"
	ANIME_RATING_PG_NOT_EQUAL     = "!pg"
	ANIME_RATING_PG_13_NOT_EQUAL  = "!pg_13"
	ANIME_RATING_R_NOT_EQUAL      = "!r"
	ANIME_RATING_R_PLUS_NOT_EQUAL = "!r_plus"
	ANIME_RATING_RX_NOT_EQUAL     = "!rx"

	ANIME_DURATION_S           = "S"
	ANIME_DURATION_D           = "D"
	ANIME_DURATION_F           = "F"
	ANIME_DURATION_S_NOT_EQUAL = "!S"
	ANIME_DURATION_D_NOT_EQUAL = "!D"
	ANIME_DURATION_F_NOT_EQUAL = "!F"

	MANGA_ORDER_ID         = "id"
	MANGA_ORDER_RANKED     = "ranked"
	MANGA_ORDER_KIND       = "kind"
	MANGA_ORDER_POPULARITY = "popularity"
	MANGA_ORDER_NAME       = "name"
	MANGA_ORDER_AIRED_ON   = "aired_on"
	MANGA_ORDER_VOLUMES    = "volumes"
	MANGA_ORDER_CHAPTERS   = "chapters"
	MANGA_ORDER_STATUS     = "status"

	MANGA_KIND_MANGA                 = "manga"
	MANGA_KIND_MANHWA                = "manhwa"
	MANGA_KIND_MANHUA                = "manhua"
	MANGA_KIND_NOVEL                 = "novel"
	MANGA_KIND_LIGHT_NOVEL           = "light_novel"
	MANGA_KIND_ONE_SHOT              = "one_shot"
	MANGA_KIND_DOUJIN                = "doujin"
	MANGA_KIND_MANGA_NOT_EQUAL       = "!manga"
	MANGA_KIND_MANHWA_NOT_EQUAL      = "!manhwa"
	MANGA_KIND_MANHUA_NOT_EQUAL      = "!manhua"
	MANGA_KIND_NOVEL_NOT_EQUAL       = "!novel"
	MANGA_KIND_LIGHT_NOVEL_NOT_EQUAL = "!light_novel"
	MANGA_KIND_ONE_SHOT_NOT_EQUAL    = "!one_shot"
	MANGA_KIND_DOUJIN_NOT_EQUAL      = "!doujin"

	MANGA_STATUS_ANONS                  = "anons"
	MANGA_STATUS_ONGOING                = "ongoing"
	MANGA_STATUS_RELEASED               = "released"
	MANGA_STATUS_PAUSED                 = "paused"
	MANGA_STATUS_DISCONTINUED           = "discontinued"
	MANGA_STATUS_ANONS_NOT_EQUAL        = "!anons"
	MANGA_STATUS_ONGOING_NOT_EQUAL      = "!ongoing"
	MANGA_STATUS_RELEASED_NOT_EQUAL     = "!released"
	MANGA_STATUS_PAUSED_NOT_EQUAL       = "!paused"
	MANGA_STATUS_DISCONTINUED_NOT_EQUAL = "!discontinued"

	PEOPLE_KIND_SEYU     = "seyu"
	PEOPLE_KIND_MANGAKA  = "mangaka"
	PEOPLE_KIND_PRODUCER = "producer"

	FAVORITES_LINKED_TYPE_ANIME     = "Anime"
	FAVORITES_LINKED_TYPE_MANGA     = "Manga"
	FAVORITES_LINKED_TYPE_RANOBE    = "Ranobe"
	FAVORITES_LINKED_TYPE_PERSON    = "Person"
	FAVORITES_LINKED_TYPE_CHARACTER = "Character"

	FAVORITES_KIND_COMMON   = "common"
	FAVORITES_KIND_SEYU     = "seyu"
	FAVORITES_KIND_MANGAKA  = "mangaka"
	FAVORITES_KIND_PRODUCER = "producer"
	FAVORITES_KIND_PERSON   = "person"

	GENRES_ANIME = "anime"
	GENRES_MANGA = "manga"

	GENERATE_GENRES_ANIME = "Anime"
	GENERATE_GENRES_MANGA = "Manga"

	UNREAD_MESSAGES_IDS_NEWS          = "news"
	UNREAD_MESSAGES_IDS_MESSAGES      = "messages"
	UNREAD_MESSAGES_IDS_NOTIFICATIONS = "notifications"

	GRAPHQL_ORDER_FIELD_ID         = "id"
	GRAPHQL_ORDER_FIELD_UPDATED_AT = "updated_at"
	GRAPHQL_ORDER_ORDER_ASC        = "asc"
	GRAPHQL_ORDER_ORDER_DESC       = "desc"
)
