name: goshikimori
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.0'
      - name: Configuration tests
        run: go test -v configuration_test.go configuration.go
      - name: GraphQL tests
        run: go test -v graphql_test.go graphql.go
      - name: Request tests
        run: go test -v ./internal/request
      - name: Concatination tests
        run: go test -v ./internal/concatenation
      - name: Neko tests
        run: go test -v ./neko
      - name: Genres tests
        run: go test -v ./genres
